### PR TITLE
windows CI

### PR DESCRIPTION
**Pull request by sakrist**
Windows tests

### CODE REVIEW

**Comment by sakrist** [comment]
Not sure if it's clean enough.

**Comment by sakrist** [comment]
Tests passed on my fork 
https://github.com/sakrist/SwiftMath/runs/1802306691?check_suite_focus=true

**Comment by sakrist** [comment]
@s1ddok 
I suggest removing `random` extension or mark it as deprecated for `Int`, `Int32`, `Float` and `Double`.  Swift has built in [random](https://developer.apple.com/documentation/swift/int/2995648-random) function for those types.

**Comment by s1ddok** [comment]
It sounds reasonable! Current random extensions were introduced before Swift's ones came out

**Comment by 3d4m-volodymyr** [comment]
Can you please release new version? Then I will be able to switch my cross platform OpenGL sample app to it.

**Comment by s1ddok** [comment]
Done

**Pull request merged**
